import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Provider from "@/components/Provider";
import AppBar from "@/components/appBar";

const geistSans = localFont({
	src: "./fonts/GeistVF.woff",
	variable: "--font-geist-sans",
});
const geistMono = localFont({
	src: "./fonts/GeistMonoVF.woff",
	variable: "--font-geist-mono",
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export const dynamic = "force-dynamic";
export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en" className="h-dvh dark">
			<body
				className={`${geistSans.className} ${geistMono.className} flex h-full flex-col`}
			>
				<Provider>
					<AppBar />
					{children}
				</Provider>
			</body>
		</html>
	);
}
