// This file is auto-generated by @hey-api/openapi-ts

import { type Options, appControllerGetHello, appControllerGetProtected, userControllerGetAllProfiles } from '../sdk.gen';
import { queryOptions } from '@tanstack/react-query';
import type { AppControllerGetHelloData, AppControllerGetProtectedData, UserControllerGetAllProfilesData } from '../types.gen';
import { client as _heyApiClient } from '../client.gen';

export type QueryKey<TOptions extends Options> = [
    Pick<TOptions, 'baseUrl' | 'body' | 'headers' | 'path' | 'query'> & {
        _id: string;
        _infinite?: boolean;
    }
];

const createQueryKey = <TOptions extends Options>(id: string, options?: TOptions, infinite?: boolean): [
    QueryKey<TOptions>[0]
] => {
    const params: QueryKey<TOptions>[0] = { _id: id, baseUrl: options?.baseUrl || (options?.client ?? _heyApiClient).getConfig().baseUrl } as QueryKey<TOptions>[0];
    if (infinite) {
        params._infinite = infinite;
    }
    if (options?.body) {
        params.body = options.body;
    }
    if (options?.headers) {
        params.headers = options.headers;
    }
    if (options?.path) {
        params.path = options.path;
    }
    if (options?.query) {
        params.query = options.query;
    }
    return [
        params
    ];
};

export const appControllerGetHelloQueryKey = (options?: Options<AppControllerGetHelloData>) => createQueryKey('appControllerGetHello', options);

export const appControllerGetHelloOptions = (options?: Options<AppControllerGetHelloData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await appControllerGetHello({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: appControllerGetHelloQueryKey(options)
    });
};

export const appControllerGetProtectedQueryKey = (options?: Options<AppControllerGetProtectedData>) => createQueryKey('appControllerGetProtected', options);

export const appControllerGetProtectedOptions = (options?: Options<AppControllerGetProtectedData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await appControllerGetProtected({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: appControllerGetProtectedQueryKey(options)
    });
};

export const userControllerGetAllProfilesQueryKey = (options?: Options<UserControllerGetAllProfilesData>) => createQueryKey('userControllerGetAllProfiles', options);

export const userControllerGetAllProfilesOptions = (options?: Options<UserControllerGetAllProfilesData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await userControllerGetAllProfiles({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: userControllerGetAllProfilesQueryKey(options)
    });
};