// This file is auto-generated by @hey-api/openapi-ts

export const ProfilesValuesSchema = {
    type: 'object',
    properties: {
        user_id: {
            type: 'string',
            description: 'O ID único do usuário (UUID)',
            example: 'a1b2c3d4-e5f6-g7h8-i9j0-k1l2m3n4o5p6'
        },
        fullname: {
            type: 'string',
            description: 'O nome completo do usuário',
            example: 'Carlos Santana'
        },
        username: {
            type: 'string',
            description: 'O nome de usuário único (para login)',
            example: 'carlossantana'
        },
        role: {
            type: 'string',
            description: 'A função (role) do usuário no sistema',
            enum: ['ADMIN', 'MODERATOR', 'USER'],
            example: 'USER'
        },
        picture: {
            type: 'object',
            description: 'A URL para a foto de perfil do usuário',
            nullable: true,
            example: 'https://minha-cdn.com/fotos/carlossantana.jpg'
        }
    },
    required: ['user_id', 'fullname', 'username', 'role', 'picture']
} as const;