// This file is auto-generated by @hey-api/openapi-ts

export type ProfilesValues = {
    /**
     * O ID único do usuário (UUID)
     */
    user_id: string;
    /**
     * O nome completo do usuário
     */
    fullname: string;
    /**
     * O nome de usuário único (para login)
     */
    username: string;
    /**
     * A função (role) do usuário no sistema
     */
    role: 'ADMIN' | 'MODERATOR' | 'USER';
    /**
     * A URL para a foto de perfil do usuário
     */
    picture: {
        [key: string]: unknown;
    } | null;
};

export type AppControllerGetHelloData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/';
};

export type AppControllerGetHelloResponses = {
    200: unknown;
};

export type AppControllerGetProtectedData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/protected';
};

export type AppControllerGetProtectedResponses = {
    200: unknown;
};

export type UserControllerGetAllProfilesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/user/profiles';
};

export type UserControllerGetAllProfilesErrors = {
    /**
     * You are not logged in
     */
    401: unknown;
    /**
     * You not have permission to access this resource
     */
    403: unknown;
};

export type UserControllerGetAllProfilesResponses = {
    /**
     * Returns all user profiles data
     */
    200: ProfilesValues;
};

export type UserControllerGetAllProfilesResponse = UserControllerGetAllProfilesResponses[keyof UserControllerGetAllProfilesResponses];

export type ClientOptions = {
    baseUrl: string;
};